spin_version = "1"
authors = ["Richard Lee <ruli3956@uni.sydney.edu.au>"]
description = "Research work for Bachelor of Science (Honours) at the University of Sydney"
name = "richard-research"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
source = "opt/wasi-python/bin/python3.wasm"
id = "python-sorting"
files = [{ source = "src", destination = "/src" }, { source = "opt", destination = "/opt" }]
environment = { PYTHONHOME = "/opt/wasi-python/lib/python3.11", PYTHONPATH = "/opt/wasi-python/lib/python3.11" }
[component.trigger]
route = "/sorting"
executor = { type = "wagi", argv = "${SCRIPT_NAME} /src/env.py ${SCRIPT_NAME} ${ARGS}" }

[[component]]
source = "opt/wasi-python/bin/python3.wasm"
id = "python-other"
files = [{ source = "src", destination = "/src" }, { source = "opt", destination = "/opt" }]
environment = { PYTHONHOME = "/opt/wasi-python/lib/python3.11", PYTHONPATH = "/opt/wasi-python/lib/python3.11" }
[component.trigger]
route = "/other"
executor = { type = "wagi", argv = "${SCRIPT_NAME} /src/others.py ${SCRIPT_NAME} ${ARGS}" }